import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={"p-10 absolute left-96 text-xl cursor-pointer font-extrabold hover:animate-pulse "}>I will be bulilding google today </h1>
      </main>

    </div>
  )
}
